if exist PACMAN.xex DEL PACMAN.xex
mads -d:VERSION=1 PACMAN.asm -o:PACMAN-ORIGINAL.xex
mads -d:VERSION=2 PACMAN.asm -o:PACMAN-ROKLAN.xex
mads -d:VERSION=3 PACMAN.asm -o:PACMAN-ATARI82.xex

mads -d:VERSION=1 -d:INTERMISSION_DEMO=1 PACMAN.asm -o:PACMAN-ORIGINAL-INTERMISSION-DEMO.xex

